### ISSUE TITLE
Improve Mobile Design

### ISSUE THREAD

**Issue by sarthak-diwan** [sarthak-diwan/jses#1]
Just make site better for mobile view! Maybe add some media queries

**Comment by byalo-zaiche** [comment]
I'm willing to make it more responsive. Assign me, please!

**Comment by SudhansuuRanjan** [comment]
I want to work on this issue please assign it to me.

**Comment by SudhansuuRanjan** [comment]
please review my pr

**Comment by sarthak-diwan** [comment]
Looking at it

**Comment by sarthak-diwan** [comment]
Actually the card still looks ugly in mobile view.. I will add 3 points for fixing that!

**Comment by shmiitg** [comment]
i would like to work on this issue, if its still open

**Comment by sarthak-diwan** [comment]
Actually, for the RSA UI fix, some changes were made to the card, which fixed It for mobile, so I am closing the issue.
