### ISSUE TITLE
Add Chaining

### ISSUE THREAD

**Issue by sarthak-diwan** [sarthak-diwan/jses#3]
Add a plus button above the textbox for chaining multiple encodings/hashing (leave encryptions for now).
Example:
MD5 + SHA256 + BASE64
Comment if you need more help explaining the issue.

**Comment by letsintegreat** [comment]
I'd like to work on this issue.

**Comment by sarthak-diwan** [comment]
Assigned

**Comment by sarthak-diwan** [comment]
In chaining the raw bytes need to used for next operation.
For example: MD5 -> SHA256 -> Base64
What the original functions do : hex(md5(data))
You are treating the hex as string
You are doing is : base64(hex(sha256(hex(md5(data)))))
What actually is needed : base64(sha256(md5(data)))

Chaining with strings makes no sense as one can easily copy paste
